[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.3
    madhephaestus/ESP32Servo@^0.13.0

[env:native]
platform = native
lib_deps =
    bblanchon/ArduinoJson@^6.21.3
